cc_library(
    name = "notification_helper",
    hdrs = ["notification_helper.h"],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
        "additional_warnings",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
    ],
)
