[workspace]
resolver = "2"
members=[
    "score/mw/log",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
log = { git = "https://github.com/qorix-group/log.git", branch = "larsp_add_fatal_loglevel",features = ["std", "fatal"]}
cc = "1.2.26"

