# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@score_baselibs//:bazel/unit_tests.bzl", "cc_gtest_unit_test")

cc_library(
    name = "arguments",
    srcs = ["arguments.cpp"],
    hdrs = ["arguments.h"],
    visibility = ["//visibility:public"],
    deps = ["@score_baselibs//score/language/safecpp/string_view:zstring_view"],
)

cc_gtest_unit_test(
    name = "unit_tests",
    srcs = ["arguments_test.cpp"],
    features = [
        "treat_warnings_as_errors",
        "additional_warnings",
        "strict_warnings",
    ],
    deps = [":arguments"],
)
