/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
#include "score/os/utils/machine_seam.h"
#include "score/os/utils/machine_seam_impl.h"

namespace score
{
namespace os
{
score::os::Machine& Machine::instance() noexcept
{
    static score::os::MachineImpl implInstance;  // LCOV_EXCL_BR_LINE
    // all branches are generated by certified compiler, no additional check necessary.
    return select_instance(implInstance);
}
}  // namespace os
}  // namespace score
