@startuml GetOwnerUid

participant SharedMemoryResource 
participant "os::Stat" as os
participant "os::Acl" as acl

[->  SharedMemoryResource: GetOwnerUid(fd)
SharedMemoryResource -> os : fstat(fd)
os -> SharedMemoryResource: return StatBuffer

SharedMemoryResource -> SharedMemoryResource: set owner_uid = StatBuffer.uid

alt StatBuffer.uid == typed memory manager uid && memory is named
    SharedMemoryResource -> acl: get_acl(fd)
    acl -> SharedMemoryResource: return acl

    SharedMemoryResource -> SharedMemoryResource: get uids with execution \n permissions from acl

    alt number of uids with exec permission != 1
        note over SharedMemoryResource
        It is impossible to determine the owner
        as mutiple uids have execution permission
        Process is terminated
        endnote
        SharedMemoryResource -> SharedMemoryResource: std::terminate()
        destroy SharedMemoryResource
    end

    SharedMemoryResource -> SharedMemoryResource: owner_uid = uid found in the acls
end

SharedMemoryResource ->[: return owner_uid

@enduml
