# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("//bazel:unit_tests.bzl", "cc_gtest_unit_test")

cc_gtest_unit_test(
    name = "test_std_arithmetic_types",
    srcs = ["test_std_arithmetic_types.cpp"],
    visibility = [
        # "@ddad//score/language/safecpp/test:__pkg__",
    ],
)
