/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
#include "score/os/stdlib_impl.h"

score::os::Stdlib& score::os::Stdlib::instance() noexcept
{
    static StdlibImpl instance{};  // LCOV_EXCL_BR_LINE : all branches are generated by certified compiler,
    // no additional check necessary
    return score::os::Stdlib::select_instance(instance);
}

std::unique_ptr<score::os::Stdlib> score::os::Stdlib::Default() noexcept
{
    return std::make_unique<StdlibImpl>();
}

/* KW_SUPPRESS_START:MISRA.PPARAM.NEEDS.CONST, MISRA.VAR.NEEDS.CONST: */
/* score::cpp::pmr::make_unique takes non-const memory_resource */
score::cpp::pmr::unique_ptr<score::os::Stdlib> score::os::Stdlib::Default(score::cpp::pmr::memory_resource* memory_resource) noexcept
/* KW_SUPPRESS_END:MISRA.PPARAM.NEEDS.CONST, MISRA.VAR.NEEDS.CONST */
{
    return score::cpp::pmr::make_unique<StdlibImpl>(memory_resource);
}
