/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/
#include "score/os/sys_uio.h"
#include "score/os/sys_uio_impl.h"

score::os::SysUio& score::os::SysUio::instance() noexcept
{
    static score::os::SysUioImpl instance{};  // LCOV_EXCL_BR_LINE : all branches are generated by certified compiler,
                                            // no additional check necessary
    return select_instance(instance);
}

score::cpp::pmr::unique_ptr<score::os::SysUio> score::os::SysUio::Default(score::cpp::pmr::memory_resource* memory_resource) noexcept
{
    return score::cpp::pmr::make_unique<score::os::SysUioImpl>(memory_resource);
}
