cc_library(
    name = "tracing_utils",
    hdrs = [
        "saturating_integral.hpp",
    ],
    tags = ["FUSA"],
    visibility = [
        "@score_baselibs//score/analysis/tracing:__subpackages__",
    ],
)
