# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

cc_library(
    name = "tracing_utils",
    hdrs = [
        "saturating_integral.hpp",
    ],
    tags = ["FUSA"],
    visibility = [
        "@score_baselibs//score/analysis/tracing:__subpackages__",
    ],
)
