# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Bazel Build (Linux)
permissions:
  contents: read
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_call:
jobs:
  linux-build-and-test:
    name: Build and Test ${{ matrix.bazel-config }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel-config: bl-x86_64-linux
            bazel-build-target: "//score/..."
            bazel-test-target: >-
              //score/...
              -//score/language/safecpp/aborts_upon_exception:abortsuponexception_toolchain_test
            bazel-test-extra-flags: ""
          - bazel-config: bl-aarch64-linux
            bazel-build-target: "//score/..."
            bazel-test-target: >-
              //score/...
              -//score/language/safecpp/aborts_upon_exception:abortsuponexception_toolchain_test
              -//score/os/test:acl_test
              -//score/os/test:errno_test
              -//score/os/test:socket_test
            bazel-test-extra-flags: "--test_timeout=180,900,2700,10800" # Increase test timeout due to QEMU emulation
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Free Disk Space (Ubuntu)
        uses: eclipse-score/cicd-workflows/.github/actions/free_disk_space@7e109c9e97670ec621adaea1c21721c18212a96d
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.job }}_${{ matrix.bazel-config }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}
      - name: Install QEMU
        if: matrix.bazel-config == 'bl-aarch64-linux'
        run: |
          sudo apt-get update
          sudo apt install -y qemu-user
      - name: Bazel Build
        run: |
          bazel build --config ${{ matrix.bazel-config }} -- ${{ matrix.bazel-build-target }}
      - name: Bazel Test
        run: |
          bazel test --config ${{ matrix.bazel-config }} ${{ matrix.bazel-test-extra-flags }} -- ${{ matrix.bazel-test-target }}
      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: bazel-testlogs-${{ matrix.bazel-config }}
          path: bazel-testlogs/**/test.log
