# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
cc_library(
    name = "random_string_test_lib",
    testonly = True,
    srcs = ["random_string.cpp"],
    hdrs = ["random_string.h"],
    visibility = [
        "@score_baselibs//score/os/test:__subpackages__",
        "@score_baselibs//score/os/utils/test:__subpackages__",
    ],
)
