# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@score-baselibs//score/language/safecpp:toolchain_features.bzl", "COMPILER_WARNING_FEATURES")

cc_library(
    name = "my_custom_type_mw_log",
    testonly = True,
    srcs = [
        "my_custom_type_mw_log.cpp",
    ],
    hdrs = [
        "my_custom_type.h",
        "my_custom_type_mw_log.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "@score-baselibs//score/mw/log:__pkg__",
        "//platform/aas/test/pas/logging/utils:__pkg__",
    ],
    deps = [
        "@score-baselibs//score/mw/log:log_stream",
    ],
)
